# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "PrivateUserSystem" ]
  pull_request:
    branches: [ "PrivateUserSystem" ]

permissions:
  contents: read

jobs:
  windows-build:

    runs-on: windows-latest

    steps:
    - uses: sayyid5416/pyinstaller@v1
      with:
          python_ver: '3.10'
          spec: 'client/bbs.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'bbs'
          options: --onefile, --name "SimpleBBS", --noconsole, 
